//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.27 at 10:10:30 PM CST 
//


package com.umsa.jaxb.bscsdegree;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CoreCourses"/>
 *         &lt;element ref="{}Electives"/>
 *         &lt;element ref="{}MathandStatistcs"/>
 *         &lt;element ref="{}OtherCourses"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "coreCourses",
    "electives",
    "mathandStatistcs",
    "otherCourses"
})
@XmlRootElement(name = "CSBSReq")
public class CSBSReq {

    @XmlElement(name = "CoreCourses", required = true)
    protected CoreCourses coreCourses;
    @XmlElement(name = "Electives", required = true)
    protected Electives electives;
    @XmlElement(name = "MathandStatistcs", required = true)
    protected MathandStatistcs mathandStatistcs;
    @XmlElement(name = "OtherCourses", required = true)
    protected OtherCourses otherCourses;

    /**
     * Gets the value of the coreCourses property.
     * 
     * @return
     *     possible object is
     *     {@link CoreCourses }
     *     
     */
    public CoreCourses getCoreCourses() {
        return coreCourses;
    }

    /**
     * Sets the value of the coreCourses property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoreCourses }
     *     
     */
    public void setCoreCourses(CoreCourses value) {
        this.coreCourses = value;
    }

    /**
     * Gets the value of the electives property.
     * 
     * @return
     *     possible object is
     *     {@link Electives }
     *     
     */
    public Electives getElectives() {
        return electives;
    }

    /**
     * Sets the value of the electives property.
     * 
     * @param value
     *     allowed object is
     *     {@link Electives }
     *     
     */
    public void setElectives(Electives value) {
        this.electives = value;
    }

    /**
     * Gets the value of the mathandStatistcs property.
     * 
     * @return
     *     possible object is
     *     {@link MathandStatistcs }
     *     
     */
    public MathandStatistcs getMathandStatistcs() {
        return mathandStatistcs;
    }

    /**
     * Sets the value of the mathandStatistcs property.
     * 
     * @param value
     *     allowed object is
     *     {@link MathandStatistcs }
     *     
     */
    public void setMathandStatistcs(MathandStatistcs value) {
        this.mathandStatistcs = value;
    }

    /**
     * Gets the value of the otherCourses property.
     * 
     * @return
     *     possible object is
     *     {@link OtherCourses }
     *     
     */
    public OtherCourses getOtherCourses() {
        return otherCourses;
    }

    /**
     * Sets the value of the otherCourses property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherCourses }
     *     
     */
    public void setOtherCourses(OtherCourses value) {
        this.otherCourses = value;
    }

}
