//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.27 at 10:10:30 PM CST 
//


package com.umsa.jaxb.bscsdegree;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}noofelecctives"/>
 *         &lt;element ref="{}abovelevel"/>
 *         &lt;element ref="{}relationwithotherelectives"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "noofelecctives",
    "abovelevel",
    "relationwithotherelectives"
})
@XmlRootElement(name = "Elective")
public class Elective {

    @XmlElement(required = true)
    protected BigInteger noofelecctives;
    @XmlElement(required = true)
    protected BigInteger abovelevel;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String relationwithotherelectives;

    /**
     * Gets the value of the noofelecctives property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNoofelecctives() {
        return noofelecctives;
    }

    /**
     * Sets the value of the noofelecctives property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNoofelecctives(BigInteger value) {
        this.noofelecctives = value;
    }

    /**
     * Gets the value of the abovelevel property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAbovelevel() {
        return abovelevel;
    }

    /**
     * Sets the value of the abovelevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAbovelevel(BigInteger value) {
        this.abovelevel = value;
    }

    /**
     * Gets the value of the relationwithotherelectives property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationwithotherelectives() {
        return relationwithotherelectives;
    }

    /**
     * Sets the value of the relationwithotherelectives property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationwithotherelectives(String value) {
        this.relationwithotherelectives = value;
    }

}
