//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.27 at 10:10:30 PM CST 
//


package com.umsa.jaxb.bscsdegree;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.umsa.jaxb.bscsdegree package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Abovelevel_QNAME = new QName("", "abovelevel");
    private final static QName _CourseNumber_QNAME = new QName("", "course_number");
    private final static QName _CourseName_QNAME = new QName("", "course_name");
    private final static QName _Subject_QNAME = new QName("", "subject");
    private final static QName _Noofelecctives_QNAME = new QName("", "noofelecctives");
    private final static QName _Relationwithotherelectives_QNAME = new QName("", "relationwithotherelectives");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.umsa.jaxb.bscsdegree
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Electives }
     * 
     */
    public Electives createElectives() {
        return new Electives();
    }

    /**
     * Create an instance of {@link Elective }
     * 
     */
    public Elective createElective() {
        return new Elective();
    }

    /**
     * Create an instance of {@link OtherCourses }
     * 
     */
    public OtherCourses createOtherCourses() {
        return new OtherCourses();
    }

    /**
     * Create an instance of {@link Course }
     * 
     */
    public Course createCourse() {
        return new Course();
    }

    /**
     * Create an instance of {@link Corecourse }
     * 
     */
    public Corecourse createCorecourse() {
        return new Corecourse();
    }

    /**
     * Create an instance of {@link CoreCourses }
     * 
     */
    public CoreCourses createCoreCourses() {
        return new CoreCourses();
    }

    /**
     * Create an instance of {@link CSBSReq }
     * 
     */
    public CSBSReq createCSBSReq() {
        return new CSBSReq();
    }

    /**
     * Create an instance of {@link MathandStatistcs }
     * 
     */
    public MathandStatistcs createMathandStatistcs() {
        return new MathandStatistcs();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "abovelevel")
    public JAXBElement<BigInteger> createAbovelevel(BigInteger value) {
        return new JAXBElement<BigInteger>(_Abovelevel_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "course_number")
    public JAXBElement<BigInteger> createCourseNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_CourseNumber_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "course_name")
    public JAXBElement<String> createCourseName(String value) {
        return new JAXBElement<String>(_CourseName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "subject")
    public JAXBElement<String> createSubject(String value) {
        return new JAXBElement<String>(_Subject_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "noofelecctives")
    public JAXBElement<BigInteger> createNoofelecctives(BigInteger value) {
        return new JAXBElement<BigInteger>(_Noofelecctives_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "relationwithotherelectives")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createRelationwithotherelectives(String value) {
        return new JAXBElement<String>(_Relationwithotherelectives_QNAME, String.class, null, value);
    }

}
